# Generated by Django 5.1.15 on 2026-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_champ',
            field=models.CharField(choices=[('text', 'Texte'), ('date', 'Date'), ('number', 'Nombre'), ('email', 'Email'), ('select', 'Liste déroulante')], max_length=50),
        ),
    ]
